#!/usr/bin/env bash
. ~/.bashrc
# skip repositories out of workspace
if [[ "`git rev-parse --show-toplevel`" = $PROJECT_HOME* ]]; then
	git_dir=$(git rev-parse --git-dir)
	ctagsify . $git_dir/tags
	cindexify
fi
