#!/usr/bin/env bash
hash glass 2>/dev/null

if [ $? = 0 ]; then
	#persist (punch) to newly created commit and reset the timer
	glass -s status -t "{{.}}" | glass punch
	glass reset
fi

if [ ! "$GIT_REFLOG_ACTION" ]; then
	git_dir=$(git rev-parse --git-dir)
	exec $git_dir/hooks/ctags
fi
