#!/usr/bin/env bash
msg=$(cat $1)
prefix=""

case $2 in
	message|template|'')
		BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`
		ISSUE=$(echo $BRANCH_NAME | grep -Eo '[[:upper:]]+-[0-9]+')

		if [ "$ISSUE" ]; then
			TYPE=$(echo $BRANCH_NAME | grep -Eo '^\w+')
			prefix="$TYPE: $ISSUE "
		fi
		;;
esac

echo -ne "${prefix}${msg}" > "$1"
