#!/usr/bin/env bash


BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`
ISSUE=`expr "$BRANCH_NAME" : '.*/\([[:upper:]]\+-[[:digit:]]\+\)'`
msg=$(cat $1)
has_issue=`expr "$msg" : "\($ISSUE\).*"`


if [ -n "$ISSUE" -a -z "$has_issue" ]; then
    echo -n "$ISSUE $msg" > $1
fi
