session_name: dotfiles
start_directory: $HOME/workspace/src/dotfiles
# options:
#   default-path: $HOME/workspace/dotfiles

windows:
  - window_name: dotfiles
    layout: even-horizontal
    panes:
      - shell_command:
        - vim
  - window_name: ''
    layout: even-horizontal
    panes:
      - shell_command:
