session_name: dotfiles
windows:
  - window_name: dotfiles
    layout: even-horizontal
    panes:
    - shell_command:
      - cd $PROJECT_HOME/dotfiles
      - vim
  - window_name: ''
    layout: even-horizontal
    - shell_command:
      - cd $PROJECT_HOME/dotfiles
