---
- hosts: localhost
  vars:
    DCONF: "{{ lookup('env', 'HOME')}}/.config/dconf"
  pre_tasks:
    - name: Install system deps
      become: yes
      apt: name={{ item }} state=present force=yes
      when: SKIP_SUDO is not defined
      with_items:
        - vim-nox
        - git
        - exuberant-ctags
        - cmake
        - python-dev
        - libyaml-dev
        - python-pygments
        - golang
        - silversearcher-ag
        - tmux
        - bash-completion
        - virtualenvwrapper
        - python-pip
        - duplicity
        - gnupg-agent
        - ncurses-term
      tags:
        - system_reqs

    - name: Install deps for GUI
      become: yes
      apt: name={{ item }} state=present force=yes
      when: "{{ SKIP_SUDO is not defined and 'DESKTOP_SESSION' in ansible_env }}"
      with_items:
        - vim-gtk3-py2
        - virtualbox
        - vagrant
      tags:
        - system_reqs_gui

  tasks:
    - name: Install Debian specific links
      file: src={{ playbook_dir }}/roles/Debian/files/{{ item.src }} dest="{{ item.path }}" state=link force=true
      with_items:
        - { src: .bashrc.Debian, path: ~/.bashrc.platform }
      tags:
        - debianconfigs

    - name: Remove dconf directory
      file: name={{ DCONF }} state="absent"
      tags:
        - dconf

    - name: Symlink dconf
      file:  src={{ playbook_dir }}/roles/Debian/dconf dest={{ DCONF }} state="link"
      tags:
        - dconf

  roles:
    - common
