---
- hosts: localhost
  gather_facts: no
  pre_tasks:
  - name: Install system deps
    become: yes
    dnf: name={{ item }} state=present
    when: SKIP_SUDO is not defined
    with_items:
      - vim
      - git
      - ctags
      - cmake
      - gcc-c++
      - python-devel
      - libyaml-devel
      - python-pygments
      - golang
      - the_silver_searcher
      - tmux
      - bash-completion
      - python-virtualenvwrapper
      - python-pip
      - duplicity
      - gnupg2
    tags:
      - system_reqs
      - redhatconfigs

  - name: Install RedHat specific links
    file: src={{ playbook_dir }}/roles/RedHat/files/{{ item.src }} dest="{{ item.path }}" state=link force=true
    with_items:
      - { src: .bashrc.RedHat, path: ~/.bashrc.platform }
    tags:
      - debianconfigs

  roles:
    - common
