---
- hosts: localhost
  gather_facts: no
  vars:
    system_packages:
      - git
      - ctags
      - cmake
      - gcc-c++
      - python-pygments
      - golang
      - the_silver_searcher
      - tmux
      - bash-completion
      - gnupg2
      #- python-devel
      #- libyaml-devel
  pre_tasks:
  - name: Install system deps
    become: yes
    dnf: name="{{ system_packages }}" state=present
    when: SKIP_SUDO is not defined
    tags:
      - system_reqs
      - redhatconfigs

  - name: Install RedHat specific links
    file: src={{ playbook_dir }}/roles/RedHat/files/{{ item.src }} dest="{{ item.path }}" state=link force=true
    with_items:
      - { src: .bashrc.RedHat, path: ~/.bashrc.platform }
    tags:
      - redhatconfigs

  roles:
    - common
