---
- hosts: localhost
  vars:
    DCONF: "{{ lookup('env', 'HOME')}}/.config/dconf"
  pre_tasks:
    - name: Install Debian specific links
      file: src={{ playbook_dir }}/roles/Debian/files/{{ item.src }} dest="{{ item.path }}" state=link force=true
      with_items:
        - { src: .bashrc.Debian, path: ~/.bashrc.platform }
      tags:
        - debianconfigs

    - name: Configure apt repositories
      become: yes
      apt_repository: repo={{ item }} validate_certs=no state=present
      when: SKIP_SUDO is not defined and ansible_distribution == 'Ubuntu'
      with_items:
        - ppa:neovim-ppa/unstable
      tags:
        - system_reqs

    - name: Setup git lfs repo
      shell: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      when: SKIP_SUDO is not defined
      tags:
        - system_reqs

    - name: Install system deps
      become: yes
      when: SKIP_SUDO is not defined
      apt:
        state: present
        force: yes
        update_cache: yes
        name:
          # - vim-nox
          - neovim
          # available only in new Debians
          #- vim-nox-py2
          - less
          - git
          - git-lfs
          - exuberant-ctags
          - cmake
          - build-essential
          - tar
          - rsync
          # - python-dev
          # - libyaml-dev
          # for pyenv python
          # - libsqlite3-dev
          # - libbz2-dev
          # - libreadline-dev
          # - python-pygments
          - silversearcher-ag
          - tmux
          - bash-completion
          - virtualenvwrapper
          # - python-pip
          # - duplicity
          # - gnupg-agent
          # terminfo database
          - ncurses-term
          # - glances
          # - npm
          # - nodejs
          - jq
      tags:
        - system_reqs

    - name: Install golang
      become: yes
      when: SKIP_SUDO is not defined
      unarchive:
        src: https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz
        dest: /usr/local/
        remote_src: yes
        creates: /usr/local/go/bin/go
      tags:
        - golang

    - name: Create go symlinks
      become: yes
      when: SKIP_SUDO is not defined
      file: src=/usr/local/go/bin/{{ item }} dest=/usr/local/bin/{{ item }} state=link
      with_items:
        - go
        - gofmt
        - godoc
      tags:
        - golang


    # - name: Install deps for GUI
    #   become: yes
    #   when: "{{ SKIP_SUDO is not defined and 'DESKTOP_SESSION' in ansible_env }}"
    #   apt: name={{ item }} state=present force=yes
    #   with_items:
    #     - vim-gtk3
    #     - vim-gtk3-py2
    #     - virtualbox
    #     - vagrant
    #   tags:
    #     - system_reqs_gui

    # - name: Install GUI debs
    #   apt: deb={{ item }} state=present
    #   when: "{{ SKIP_SUDO is not defined and 'DESKTOP_SESSION' in ansible_env }}"
    #   with_items:
    #     - "https://atom-installer.github.com/v1.10.2/atom-amd64.deb"
    #   tags:
    #     - system_reqs_gui
    #     - system_reqs_debs

  tasks:
    - name: Remove dconf directory
      file: name={{ DCONF }} state="absent"
      tags:
        - dconf

    - name: Symlink dconf
      file:  src={{ playbook_dir }}/roles/Debian/dconf dest={{ DCONF }} state="link"
      tags:
        - dconf

  roles:
    - common
