---
- hosts: localhost
  #gather_facts: no
  vars:
    mas_installed_apps:
      - id: 1356178125
        name: Outline-Secure internet access

    homebrew_installed_packages:
      - cask
      - coreutils
      # - name: cmake
      #   install_options: --formula
      - git
      - git-lfs
      - python
      - pipx
      - neovim
      - ctags
      - bash
      - bash-completion
      - tmux
      - sd
      - fd
      - ripgrep
      - reattach-to-user-namespace
      - go
      - gpg
      # - gpg-agent
      # - fswatch
      - sf-pwgen
      # - parallel
    homebrew_cask_apps:
        # - font-iosevka
        - slack
        - karabiner-elements
        - spectacle
        - iterm2
        - telegram
        # - microsoft-office
        # - cloudflare-warp
        # - intellij-idea-ce
        # - yandexdisk
        # - virtualbox
        # - virtualbox-extension-pack
        # - vagrant
        # - transmission
        # - gimp
    dockitems_remove:
      - FaceTime
      - Music
      - Keynote
      - Numbers
      - Pages
      - Freeform
      - Maps
      - TV
    dockitems_persist:
      - name: "Visual Studio Code Insiders"
        path: "/Applications/Visual Studio Code - Insiders.app/"
        pos: 5
    PREFERENCES: "{{ lookup('env', 'HOME')}}/Library/Preferences"
  environment:
    GIT_TEMPLATE_DIR: ""

  roles:
    - geerlingguy.mac.homebrew
    # - geerlingguy.mac.mas
    - geerlingguy.mac.dock
    - common

  tasks:
    - name: Stat preferences
      stat: path={{ PREFERENCES }}
      register: preferences_stat
      tags:
        - symlink_preferences

    - name: Remove acls
      shell: /bin/chmod -a 'group:everyone deny delete' {{ PREFERENCES }} || true
      when: preferences_stat.stat.exists
      tags:
        - symlink_preferences

    - name: Symlink preferences
      command:  ln -sf {{ item }} {{ PREFERENCES }}/
      with_fileglob:
        - "{{ playbook_dir }}/roles/Darwin/Preferences/*"
        - "{{ playbook_dir }}/roles/Darwin/Preferences/.??*"
      tags:
        - symlink_preferences

    - name: Stop preferences daemon
      command: pkill -U {{ lookup('env', 'USER') }} cfprefsd
      tags:
        - symlink_preferences
        - stop_pref_daemon

    - name: Ensure application directories exist
      file: path="{{ item }}" state=directory
      with_items:
        - "~/.config/karabiner/"
      tags:
        - osxconfigs

    - name: Install OSX specific links
      file: src={{ playbook_dir }}/roles/Darwin/files/{{ item.src }} dest="{{ item.path }}" state=link force=true
      with_items:
        - { src: .tmux.Darwin.conf, path: ~/.tmux.platform.conf }
        - { src: .bashrc.Darwin, path: ~/.bashrc.platform }
        - { src: karabiner.json, path: "~/.config/karabiner/karabiner.json" }
        - { src: .gitattributes.Darwin, path: ".gitattributes" }

      tags:
        - osxconfigs

    - name: Install fonts
      file: src={{ playbook_dir }}/.fonts/Singularity.ttf dest=~/Library/Fonts/Singularity.ttf state=link force=true
      tags:
        - install_fonts

    - name: Autohide dock
      ansible.builtin.command:
        cmd: defaults write com.apple.Dock autohide -bool true
      changed_when: true
      notify: "Kill Dock"

    - name: Disable mru spaces
      ansible.builtin.command:
        cmd: defaults write com.apple.dock mru-spaces -bool false
      changed_when: true

    - name: Enable key repeate for VSCodeInsiders + Vim
      ansible.builtin.command:
        cmd: defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false
      changed_when: true

    #- name: Install atom packages
    #  command: apm install {{ item }}
    #  with_items:
    #    - vim-mode
    #    - ex-mode
    #    - easy-motion-redux
    #    - autocomplete-python
    #    # - autocomplete-go
    #  tags:
    #    - install_atom_packages

  handlers:
    - name: Kill Dock
      ansible.builtin.command: killall Dock
