---
- hosts: localhost
  #gather_facts: no
  vars:
    homebrew_install_path: "/usr/local/Homebrew"
    homebrew_installed_packages:
      - cask
      - coreutils
      - cmake
      - git
      - git-lfs
      - python
      - neovim
      - ctags
      - bash-completion
      - tmux
      - fd
      - ripgrep
      - reattach-to-user-namespace
      - go
      - gpg
      # - gpg-agent
      # - fswatch
      - sf-pwgen
      # - parallel
    # homebrew_taps:
    #   - homebrew/cask-fonts
    homebrew_cask_apps:
        # - font-iosevka
        - slack
        - karabiner-elements
        - spectacle
        - iterm2
        - telegram
        - docker
        - microsoft-office
        - cloudflare-warp
        # - intellij-idea-ce
        # - yandexdisk
        # - virtualbox
        # - virtualbox-extension-pack
        # - vagrant
        # - transmission
        # - gimp
    PREFERENCES: "{{ lookup('env', 'HOME')}}/Library/Preferences"
  environment:
    GIT_TEMPLATE_DIR: ""

  tasks:
    - name: Stat preferences
      stat: path={{ PREFERENCES }}
      register: preferences_stat
      tags:
        - symlink_preferences

    - name: Remove acls
      shell: /bin/chmod -a 'group:everyone deny delete' {{ PREFERENCES }} || true
      when: preferences_stat.stat.exists
      tags:
        - symlink_preferences

    - name: Symlink preferences
      command:  ln -sf {{ item }} {{ PREFERENCES }}/
      with_fileglob:
        - "{{ playbook_dir }}/roles/Darwin/Preferences/*"
        - "{{ playbook_dir }}/roles/Darwin/Preferences/.??*"
      tags:
        - symlink_preferences

    - name: Stop preferences daemon
      command: pkill -U {{ lookup('env', 'USER') }} cfprefsd
      tags:
        - symlink_preferences
        - stop_pref_daemon

    - name: install python packages
      pip: name={{ item }}
      with_items:
        - pipenv
        - neovim
        # - ansible
        # - glances
        # - objgraph
      tags:
        - install_python_packages

    - name: Ensure application directories exist
      file: path="{{ item }}" state=directory
      with_items:
        - "~/.config/karabiner/"
      tags:
        - osxconfigs

    - name: Install OSX specific links
      file: src={{ playbook_dir }}/roles/Darwin/files/{{ item.src }} dest="{{ item.path }}" state=link force=true
      with_items:
        - { src: .tmux.Darwin.conf, path: ~/.tmux.platform.conf }
        - { src: .bashrc.Darwin, path: ~/.bashrc.platform }
        - { src: karabiner.json, path: "~/.config/karabiner/karabiner.json" }
        - { src: .gitattributes.Darwin, path: ".gitattributes" }

      tags:
        - osxconfigs

    - name: Install fonts
      file: src={{ playbook_dir }}/.fonts/Singularity.ttf dest=~/Library/Fonts/Singularity.ttf state=link force=true
      tags:
        - install_fonts

    #- name: Install atom packages
    #  command: apm install {{ item }}
    #  with_items:
    #    - vim-mode
    #    - ex-mode
    #    - easy-motion-redux
    #    - autocomplete-python
    #    # - autocomplete-go
    #  tags:
    #    - install_atom_packages

  roles:
    - geerlingguy.mac.homebrew
    - common
