---
- hosts: localhost
  gather_facts: no
  pre_tasks:
  - name: Install system deps
    become: yes
    apt: name={{ item }} state=present force=yes
    when: SKIP_SUDO is not defined
    with_items:
      - vim-nox
      - git
      - exuberant-ctags
      - cmake
      - python-dev
      - libyaml-dev
      - python-pygments
      - golang
      - silversearcher-ag
      - tmux
      - bash-completion
      - virtualenvwrapper
      - python-pip
      - duplicity
      - gnupg-agent
    tags:
      - system_reqs

  - name: Install Debian specific links
    file: src={{ playbook_dir }}/roles/Debian/files/{{ item.src }} dest="{{ item.path }}" state=link force=true
    with_items:
      - { src: .bashrc.Debian, path: ~/.bashrc.platform }
    tags:
      - debianconfigs

  roles:
    - common
