---
- hosts: localhost
  vars:
    homebrew_installed_packages:
      - brew-cask
      - coreutils
      - git
      - vim
      - ctags
      - bash-completion
      - tmux
      - the_silver_searcher
      - reattach-to-user-namespace
      - go
    homebrew_taps:
        - caskroom/cask
  tasks:
    - name: install casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - google-chrome
        - seil
        - karabiner
        - spectacle
        - iterm2
        - skype
        - vlc
        - libreoffice
        - intellij-idea-ce

    - name: Install OSX specific links
      file: src={{ playbook_dir }}/roles/Darwin/files/{{ item.src }} dest={{ item.path }} state=link force=true
      with_items:
        - { src: .tmux.Darwin.conf, path: ~/.tmux.platform.conf }
        - { src: .bashrc.Darwin, path: ~/.bashrc.platform }
        - { src: org.pqrs.Karabiner.plist, path: ~/Library/Preferences/org.pqrs.Karabiner.plist }
        - { src: org.pqrs.Seil.plist, path: ~/Library/Preferences/org.pqrs.Seil.plist }
        - { src: com.googlecode.iterm2.plist, path: ~/Library/Preferences/com.googlecode.iterm2.plist }
        - { src: com.apple.universalaccess.plist, path: ~/Library/Preferences/com.apple.universalaccess.plist }
        - { src: com.apple.symbolichotkeys.plist, path: ~/Library/Preferences/com.apple.symbolichotkeys.plist }
        - { src: com.google.Chrome.plist, path: ~/Library/Preferences/com.google.Chrome.plist }

      tags:
        - osxconfigs

  roles:
    - geerlingguy.homebrew
    - common
