---
- hosts: localhost
  vars:
    homebrew_installed_packages:
      - brew-cask
      - coreutils
      - git
      - vim
      - ctags
      - bash-completion
      - tmux
      - the_silver_searcher
      - reattach-to-user-namespace
      - go
    homebrew_taps:
        - caskroom/cask
  tasks:
    - name: install casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - google-chrome
        - seil
        - karabiner
        - spectacle
        - iterm2
        - skype
        - vlc
        - libreoffice
        - intellij-idea-ce

    - name: Install OSX specific links
      file: src={{ playbook_dir }}/{{ item }} dest=~/{{ item }} state=link force=true
      with_items:
        - .tmux-osx.conf

  roles:
    - geerlingguy.homebrew
    - common
