---
- hosts: localhost
  gather_facts: no
  vars:
    homebrew_installed_packages:
      - brew-cask
      - coreutils
      - python
      - cmake
      - git
      - vim
      - ctags
      - bash-completion
      - tmux
      - the_silver_searcher
      - reattach-to-user-namespace
      - go
      - glide
      - unrar
      - docker
      - boot2docker
      - gpg
      - gpg-agent
      - fswatch
      - npm
      - hub
      - gist
      - sf-pwgen
      - parallel
    homebrew_taps:
        - caskroom/cask
        - caskroom/versions
    PREFERENCES: "{{ lookup('env', 'HOME')}}/Library/Preferences"
  environment:
    GIT_TEMPLATE_DIR: ""

  tasks:
    - name: Check preferences
      command: test -L {{ PREFERENCES }}
      register: is_symlink_check
      ignore_errors: yes
      tags:
        - move_preferences

    - name: Remove empty dirs in preferences
      command: find {{ PREFERENCES }} -type d -empty -delete
      when: is_symlink_check.rc
      tags:
        - move_preferences

    - name: Move preferences
      shell: shopt -s nullglob && mv {{ PREFERENCES }}/* {{ PREFERENCES }}/.??* {{ playbook_dir }}/roles/Darwin/Preferences/
      when: is_symlink_check.rc
      tags:
        - move_preferences

    - name: Remove empty directory
      command: rmdir {{ PREFERENCES }}
      become: yes
      when: is_symlink_check.rc

      tags:
        - move_preferences

    - name: Symlink preferences
      command:  ln -s {{ playbook_dir }}/roles/Darwin/Preferences {{ PREFERENCES }}
      when: is_symlink_check.rc

      tags:
        - move_preferences

    - name: Stop preferences daemon
      command: pkill -U {{ lookup('env', 'USER') }} cfprefsd
      tags:
        - stop_pref_daemon

    - name: install casks
      homebrew_cask: name='{{ item }}' state=present
      with_items:
        - google-chrome
        - seil
        - karabiner
        - spectacle
        - iterm2-beta
        - skype
        - vlc
        - libreoffice
        - intellij-idea-ce
        # - yandexdisk
        - adium
        - virtualbox
        - virtualbox-extension-pack
        - vagrant
        - anaconda
        - transmission
        - gimp
        - toggldesktop
        - atom
      tags:
        - install_casks

    - name: install node packages
      npm: name={{ item }} global=yes
      with_items:
        - jshint
      tags:
        - install_node_packages

    - name: install python packages
      pip: name={{ item }}
      with_items:
        - virtualenvwrapper
        - ansible
        - glances
        - objgraph
      tags:
        - install_python_packages

    # - name: install jupiter plugins
    #   shell: "jupyter nbextension install https://rawgithub.com/lambdalisue/jupyter-vim-binding/master/vim_binding.js --nbextensions=$(jupyter --data-dir)/nbextensions/vim_binding"
    #   tags:
    #     - configure_jupiter

    # - name: enable jupiter plugins
    #   command: "jupyter nbextension enable vim_binding/vim_binding"
    #   tags:
    #     - configure_jupiter

    - name: Ensure application directories exist
      file: path="{{ item }}" state=directory
      with_items:
        - "~/Library/Application Support/Karabiner/"
      tags:
        - osxconfigs

    - name: Install OSX specific links
      file: src={{ playbook_dir }}/roles/Darwin/files/{{ item.src }} dest="{{ item.path }}" state=link force=true
      with_items:
        - { src: .tmux.Darwin.conf, path: ~/.tmux.platform.conf }
        - { src: .bashrc.Darwin, path: ~/.bashrc.platform }
        - { src: private.xml, path: "~/Library/Application Support/Karabiner/private.xml" }

      tags:
        - osxconfigs

    - name: Install fonts
      file: src={{ playbook_dir }}/fonts/Singularity.ttf dest=~/Library/Fonts/Singularity.ttf state=link force=true
      tags:
        - install_fonts

    - name: Install atom packages
      command: apm install {{ item }}
      with_items:
        - vim-mode
        - ex-mode
        - easy-motion-redux
      tags:
        - install_atom_packages

  roles:
    - geerlingguy.homebrew
    - common
