#!/bin/bash
# This hook is run after every virtualenv is activated.
if [ -f "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME"  ]; then
	virtualenvwrapper_cd  `cat "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME"`
else
	PROJ_NAME=`basename $VIRTUAL_ENV`
	if [ -d "$PROJECT_HOME/$PROJ_NAME"  ]; then
		echo "$PROJECT_HOME/$PROJ_NAME" > "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME"
		virtualenvwrapper_cd "$PROJECT_HOME/$PROJ_NAME"
	else
		echo "Please, cd to the project root and run echo \`pwd\` > $VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME"
	fi
fi
