#!/bin/bash
# This hook is run after a new virtualenv is activated.

# install linter
# install syntax highlighter for less preprocessor
# install debugger
pip install \
	pylint \
	pdbpp \
	isort \
	neovim
