---

- name: Install dotfiles symlinks
  file: src={{ playbook_dir }}/{{ item }} dest=~/{{ item }} state=link force=true
  with_items:
    - .ackrc
    - .agignore
    - .backup.exclude.list
    - .bash_functions
    - .bash_profile
    - .bashrc
    - .ctags
    - .dir_colors
    - .git_template
    - .gitattributes
    - .gitconfig
    - .gnupg
    - .hgrc
    - .ideavimrc
    - .jshintrc
    - .pdbrc
    - .pdbrc.py
    - .pylama.ini
    - .pythonrc
    - .screenrc
    - .termcap
    - .terminfo
    - .tmux.conf
    - .vim
    - .vimrc
  tags:
    - links

- stat: path={{ playbook_dir }}/.bashrc.local
  register: bashrclocal
  tags:
    - links

- name: Install optional local profile
  file: src={{ playbook_dir }}/.bashrc.local dest=~/.bashrc.local state=link force=true
  when: bashrclocal.stat.exists
  tags:
    - links

- stat: path={{ playbook_dir }}/.gitconfig.local
  register: gitconfiglocal
  tags:
    - links

- name: Install optional local gitconfig
  file: src={{ playbook_dir }}/.gitconfig.local dest=~/.gitconfig.local state=link force=true
  when: gitconfiglocal.stat.exists
  tags:
    - links

- stat: path={{ playbook_dir }}/.tmuxp
  register: tmuxp
  tags:
    - links

- name: Check tmuxp dir
  file: src={{ playbook_dir }}/.tmuxp dest=~/.tmuxp state=link force=true
  when: tmuxp.stat.exists and tmuxp.stat.isdir
  tags:
    - links

- name: Install gitignore symlink
  file: src={{ playbook_dir }}/gitignore dest=~/.gitignore state=link force=true
  tags:
    - links

- name: get root HOME
  shell: echo $HOME
  when: SKIP_SUDO is not defined
  sudo: yes
  register: root_home
  tags:
    - links

- name: Install dotfiles symlinks to root
  file: src={{ playbook_dir }}/{{ item }} dest={{ root_home.stdout }}/{{ item }} state=link force=true
  when: SKIP_SUDO is not defined
  sudo: yes
  with_items:
    - .termcap
    - .terminfo
  tags:
    - links

- name: Create required directories
  file: path={{ item }} state=directory
  with_items:
    - ~/go
    - ~/envs
    - ~/.config
  tags:
    - links

- name: Install extra symlinks
  file: src={{ playbook_dir }}/{{ item.path }} dest=~/{{ item.dest }} state=link force=true
  with_items:
    - { path: 'bin', dest: 'bin' }
    - { path: 'envs/postactivate', dest: 'envs/postactivate' }
    - { path: 'envs/postmkvirtualenv', dest: 'envs/postmkvirtualenv' }
    - { path: 'config/pudb', dest: '.config/pudb' }
    - { path: '.vim', dest: '.config/nvim' }
  tags:
    - links

- name: Install neobundle
  git: repo=git@github.com:Shougo/neobundle.vim.git dest={{ playbook_dir }}/.vim/bundle/neobundle.vim

- name: Install global python packages
  pip: name={{ item }}
  with_items:
    - neovim
    - tmuxp
  when: SKIP_SUDO is not defined
  sudo: yes
  tags:
    - pippackages

- name: Install go tools
  command: go get github.com/junkblocker/codesearch/...
  environment:
    GOPATH: "{{ lookup('ENV', 'HOME') }}/go"
  when: SKIP_SUDO is not defined
  tags:
    - gotools
