---
- hosts: localhost
  vars:
    homebrew_installed_packages:
      - brew-cask
      - coreutils
      - git
      - vim
      - ctags
      - bash-completion
      - tmux
      - the_silver_searcher
    homebrew_taps:
        - caskroom/cask
  tasks:
    - name: install casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - google-chrome
        - seil
        - karabiner
        - iterm2
        - skype
        - vlc
        - libreoffice
        - intellij-idea-ce
  roles:
    - { role: geerlingguy.homebrew }
