---
- name: Install system deps
  sudo: yes
  zypper: name={{ item }} state=present
  with_items:
    - git-core
    - ctags
    - go
    - the_silver_searcher
    - tmux
    - bash-completion
    - python-virtualenvwrapper
