---
- name: Install system deps
  sudo: yes
  zypper: name={{ item }} state=present
  with_items:
    - git-core
    - ctags
    - cmake
    - gcc-c++
    - python-devel
    - go
    - the_silver_searcher
    - tmux
    - bash-completion
    - python-virtualenvwrapper

- name: Install extra fonts
  sudo: yes
  file: src={{ playbook_dir }}/fonts/Singularity.ttf dest=/usr/share/fonts/truetype/Singularity.ttf state=link force=true

- name: Update font database
  sudo: yes
  command: /usr/sbin/fonts-config

- name: Create required directories
  file: path={{ item }} state=directory
  with_items:
    - ~/.kde4/share/apps/konsole

- name: Configure KDE4 apps
  file: src={{ playbook_dir }}/kde4/share/apps/{{ item.path }} dest=~/.kde4/share/apps/{{ item.dest }} state=link force=true
  with_items:
    - { path: 'konsole/Shell.profile', dest: 'konsole/Shell.profile' }
